name: Build SF3000 Libretro Cores

on:
  workflow_dispatch:
    inputs:
      cores:
        description: "Build cores (empty = default list)"
        required: false
        default: ""

  push:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

    # 拉源码
    - name: Checkout
      uses: actions/checkout@v4


    # 构建docker环境
    - name: Build Docker image
      run: |
        docker build \
          -t sf3000-builder .


    # clone cores + build
    - name: Build cores
      run: |
        mkdir -p build

        if [ -z "${{ github.event.inputs.cores }}" ]; then

          docker run --rm \
            -v $PWD:/work \
            sf3000-builder \
            bash -c "
              chmod +x scripts/*.sh &&
              scripts/core.sh &&
              scripts/build.sh
            "

        else

          docker run --rm \
            -v $PWD:/work \
            sf3000-builder \
            bash -c "
              chmod +x scripts/*.sh &&
              scripts/core.sh &&
              scripts/build.sh ${{ github.event.inputs.cores }}
            "

        fi


    # 上传结果
    - name: Upload cores
      uses: actions/upload-artifact@v4
      with:
        name: sf3000-libretro-cores
        path: build/*.so
